export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAILURE = 'FETCH_WEATHER_DATA_FAILURE';
export const GET_CITY_NAME = 'GET_CITY_NAME';
export const GET_CITY_NAME_FAILURE = 'GET_CITY_NAME_FAILURE';
